import { Course, LiveClass, Achievement, Scholarship, Notification, User } from '@/lib/types';

export const currentUser: User = {
  id: '1',
  name: 'Alex Johnson',
  email: 'alex@skillhub.com',
  avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face',
  role: 'student',
};

export const courses: Course[] = [
  {
    id: '1',
    title: 'Complete Web Development Bootcamp',
    instructor: 'Dr. Sarah Chen',
    instructorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=face',
    thumbnail: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=400&h=250&fit=crop',
    rating: 4.9,
    students: 15234,
    progress: 68,
    price: 99.99,
    duration: '42 hours',
    level: 'Beginner',
    category: 'Development',
    description: 'Learn HTML, CSS, JavaScript, React, Node.js, and more!',
    lessonsCount: 285,
  },
  {
    id: '2',
    title: 'Data Science & Machine Learning',
    instructor: 'Prof. Michael Torres',
    instructorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=250&fit=crop',
    rating: 4.8,
    students: 12890,
    progress: 35,
    price: 129.99,
    duration: '56 hours',
    level: 'Intermediate',
    category: 'Data Science',
    description: 'Master Python, Pandas, NumPy, Scikit-learn, and TensorFlow.',
    lessonsCount: 320,
  },
  {
    id: '3',
    title: 'UI/UX Design Masterclass',
    instructor: 'Emma Williams',
    instructorAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face',
    thumbnail: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=250&fit=crop',
    rating: 4.9,
    students: 9876,
    progress: 100,
    price: 89.99,
    duration: '28 hours',
    level: 'Beginner',
    category: 'Design',
    description: 'Create beautiful user interfaces and seamless experiences.',
    lessonsCount: 156,
  },
  {
    id: '4',
    title: 'Digital Marketing Strategy',
    instructor: 'James Rodriguez',
    instructorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=250&fit=crop',
    rating: 4.7,
    students: 8543,
    price: 79.99,
    duration: '18 hours',
    level: 'Beginner',
    category: 'Marketing',
    description: 'Learn SEO, Social Media, PPC, and Content Marketing.',
    lessonsCount: 98,
  },
  {
    id: '5',
    title: 'Mobile App Development with Flutter',
    instructor: 'Dr. Lisa Park',
    instructorAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&h=100&fit=crop&crop=face',
    thumbnail: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400&h=250&fit=crop',
    rating: 4.8,
    students: 7234,
    progress: 22,
    price: 109.99,
    duration: '36 hours',
    level: 'Intermediate',
    category: 'Development',
    description: 'Build cross-platform mobile apps with Flutter and Dart.',
    lessonsCount: 198,
  },
  {
    id: '6',
    title: 'Cybersecurity Fundamentals',
    instructor: 'Robert Kim',
    instructorAvatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&h=100&fit=crop&crop=face',
    thumbnail: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=250&fit=crop',
    rating: 4.9,
    students: 6890,
    price: 149.99,
    duration: '48 hours',
    level: 'Advanced',
    category: 'Security',
    description: 'Protect systems and networks from cyber threats.',
    lessonsCount: 245,
  },
];

export const liveClasses: LiveClass[] = [
  {
    id: '1',
    title: 'React Hooks Deep Dive',
    instructor: 'Dr. Sarah Chen',
    course: 'Complete Web Development Bootcamp',
    startTime: new Date(Date.now() + 1000 * 60 * 30).toISOString(),
    duration: 90,
    attendees: 156,
    isLive: false,
  },
  {
    id: '2',
    title: 'Building Neural Networks from Scratch',
    instructor: 'Prof. Michael Torres',
    course: 'Data Science & Machine Learning',
    startTime: new Date(Date.now() + 1000 * 60 * 60 * 2).toISOString(),
    duration: 120,
    attendees: 89,
    isLive: false,
  },
  {
    id: '3',
    title: 'Design Systems Workshop',
    instructor: 'Emma Williams',
    course: 'UI/UX Design Masterclass',
    startTime: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    duration: 60,
    attendees: 234,
    isLive: true,
  },
];

export const achievements: Achievement[] = [
  {
    id: '1',
    title: 'First Steps',
    description: 'Complete your first lesson',
    icon: '🎯',
    earnedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    type: 'badge',
  },
  {
    id: '2',
    title: 'Week Warrior',
    description: 'Study for 7 consecutive days',
    icon: '🔥',
    earnedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString(),
    type: 'badge',
  },
  {
    id: '3',
    title: 'UI/UX Design Masterclass',
    description: 'Certificate of Completion',
    icon: '🏆',
    earnedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
    type: 'certificate',
  },
];

export const scholarships: Scholarship[] = [
  {
    id: '1',
    title: 'Tech for All Initiative',
    sponsor: 'Global Tech Foundation',
    amount: 50000,
    beneficiaries: 125,
    status: 'active',
    description: 'Supporting underrepresented groups in technology education.',
  },
  {
    id: '2',
    title: 'Women in STEM Scholarship',
    sponsor: 'EmpowerHer Corp',
    amount: 75000,
    beneficiaries: 200,
    status: 'active',
    description: 'Empowering women to pursue careers in science and technology.',
  },
];

export const notifications: Notification[] = [
  {
    id: '1',
    title: 'Live Class Starting Soon',
    message: 'React Hooks Deep Dive starts in 30 minutes',
    type: 'class',
    timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    read: false,
  },
  {
    id: '2',
    title: 'Achievement Unlocked!',
    message: 'You earned the "Community Helper" badge',
    type: 'success',
    timestamp: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    read: false,
  },
  {
    id: '3',
    title: 'Assignment Due Tomorrow',
    message: 'Web Development Project #3 is due in 24 hours',
    type: 'warning',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    read: true,
  },
];

export const teacherStats = {
    totalStudents: 15234,
    courseRevenue: 125890,
    averageRating: 4.85,
    activeCourses: 8,
    totalViews: 89234,
    completionRate: 76,
    monthlyEarnings: [
      { month: 'Jan', earnings: 8500 },
      { month: 'Feb', earnings: 9200 },
      { month: 'Mar', earnings: 11000 },
      { month: 'Apr', earnings: 10500 },
      { month: 'May', earnings: 12300 },
      { month: 'Jun', earnings: 14200 },
    ],
  };
  
  export const sponsorStats = {
    scholarshipsFunded: 4,
    studentsHelped: 764,
    totalBudget: 255000,
    budgetUsed: 198000,
    impactScore: 94,
    csrRating: 'A+',
    monthlyImpact: [
      { month: 'Jan', students: 45, budget: 15000 },
      { month: 'Feb', students: 62, budget: 22000 },
      { month: 'Mar', students: 78, budget: 28000 },
      { month: 'Apr', students: 125, budget: 35000 },
      { month: 'May', students: 198, budget: 48000 },
      { month: 'Jun', students: 256, budget: 50000 },
    ],
  };
  
  export const adminStats = {
    totalUsers: 52890,
    totalRevenue: 1250000,
    activeCourses: 156,
    systemHealth: 99.8,
    newUsersToday: 234,
    activeSessionsNow: 1567,
    pendingApprovals: 12,
    reportedContent: 3,
    userGrowth: [
      { month: 'Jan', users: 35000, revenue: 180000 },
      { month: 'Feb', users: 38000, revenue: 195000 },
      { month: 'Mar', users: 42000, revenue: 210000 },
      { month: 'Apr', users: 45000, revenue: 225000 },
      { month: 'May', users: 49000, revenue: 240000 },
      { month: 'Jun', users: 52890, revenue: 260000 },
    ],
    usersByRole: [
      { role: 'Students', count: 48500 },
      { role: 'Teachers', count: 890 },
      { role: 'Sponsors', count: 245 },
      { role: 'Admins', count: 15 },
    ],
  };
