
import { Course, LiveClass, Achievement, Scholarship } from '@/lib/types';

export const courses: Omit<Course, 'id'>[] = [
    {
      title: 'Complete Web Development Bootcamp',
      instructor: 'Dr. Sarah Chen',
      instructorId: 'placeholder-teacher-1',
      instructorAvatar: 'https://i.pravatar.cc/150?u=sarah',
      thumbnail: 'https://picsum.photos/seed/webdev/600/400',
      rating: 4.9,
      students: 15234,
      progress: 68,
      price: 99.99,
      duration: '42 hours',
      level: 'Beginner',
      category: 'Development',
      description: 'Learn HTML, CSS, JavaScript, React, Node.js, and more!',
      lessonsCount: 285,
    },
    {
      title: 'Data Science & Machine Learning',
      instructor: 'Prof. Michael Torres',
      instructorId: 'placeholder-teacher-1',
      instructorAvatar: 'https://i.pravatar.cc/150?u=michael',
      thumbnail: 'https://picsum.photos/seed/datasci/600/400',
      rating: 4.8,
      students: 12890,
      progress: 35,
      price: 129.99,
      duration: '56 hours',
      level: 'Intermediate',
      category: 'Data Science',
      description: 'Master Python, Pandas, NumPy, Scikit-learn, and TensorFlow.',
      lessonsCount: 320,
    },
    {
        title: 'UI/UX Design Masterclass',
        instructor: 'Emma Williams',
        instructorId: 'placeholder-teacher-2',
        instructorAvatar: 'https://i.pravatar.cc/150?u=emma',
        thumbnail: 'https://picsum.photos/seed/uiux/600/400',
        rating: 4.9,
        students: 9876,
        progress: 100,
        price: 89.99,
        duration: '28 hours',
        level: 'Beginner',
        category: 'Design',
        description: 'Create beautiful user interfaces and seamless experiences.',
        lessonsCount: 156,
      },
      {
        title: 'Digital Marketing Strategy',
        instructor: 'James Rodriguez',
        instructorId: 'placeholder-teacher-2',
        instructorAvatar: 'https://i.pravatar.cc/150?u=james',
        thumbnail: 'https://picsum.photos/seed/marketing/600/400',
        rating: 4.7,
        students: 8543,
        price: 79.99,
        duration: '18 hours',
        level: 'Beginner',
        category: 'Marketing',
        description: 'Learn SEO, Social Media, PPC, and Content Marketing.',
        lessonsCount: 98,
      },
];
  
export const liveClasses: Omit<LiveClass, 'id'>[] = [
    {
      title: 'React Hooks Deep Dive',
      instructor: 'Dr. Sarah Chen',
      course: 'Complete Web Development Bootcamp',
      startTime: new Date(Date.now() + 1000 * 60 * 30).toISOString(),
      duration: 90,
      attendees: 156,
      isLive: false,
    },
    {
      title: 'Building Neural Networks from Scratch',
      instructor: 'Prof. Michael Torres',
      course: 'Data Science & Machine Learning',
      startTime: new Date(Date.now() + 1000 * 60 * 60 * 2).toISOString(),
      duration: 120,
      attendees: 89,
      isLive: false,
    },
    {
      title: 'Design Systems Workshop',
      instructor: 'Emma Williams',
      course: 'UI/UX Design Masterclass',
      startTime: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
      duration: 60,
      attendees: 234,
      isLive: true,
    },
  ];
  
export const achievements: Omit<Achievement, 'id'>[] = [
    {
      title: 'First Steps',
      description: 'Complete your first lesson',
      icon: '🎯',
      earnedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
      type: 'badge',
    },
    {
      title: 'Week Warrior',
      description: 'Study for 7 consecutive days',
      icon: '🔥',
      earnedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 14).toISOString(),
      type: 'badge',
    },
    {
      title: 'UI/UX Design Masterclass',
      description: 'Certificate of Completion',
      icon: '🏆',
      earnedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
      type: 'certificate',
    },
  ];
  
export const scholarships: Omit<Scholarship, 'id'>[] = [
    {
      title: 'Tech for All Initiative',
      sponsor: 'Global Tech Foundation',
      amount: 50000,
      beneficiaries: 125,
      status: 'active',
      description: 'Supporting underrepresented groups in technology education.',
    },
    {
      title: 'Women in STEM Scholarship',
      sponsor: 'EmpowerHer Corp',
      amount: 75000,
      beneficiaries: 200,
      status: 'active',
      description: 'Empowering women to pursue careers in science and technology.',
    },
];
